#!/usr/bin/env python3
"""Pin dispatch entries and handler bodies, including return expressions.
This is a source inventory, not a C++ parser or an ISA correctness proof.
"""
import re, pathlib, hashlib, json
root=pathlib.Path(__file__).resolve().parent.parent
src=root/'NooDS-Wii'; out=root/'docs/jit'; out.mkdir(parents=True,exist_ok=True)
lookup=(src/'interpreter_lookup.cpp').read_text()
manifest={}
for mode,count in [('arm',4096),('thumb',1024)]:
    match=re.search(r'Interpreter::'+mode+r'Instrs\[\]\)\(uint(?:32|16)_t\)\s*=\s*\{(.*?)\};',lookup,re.S)
    if not match: raise SystemExit('dispatch initializer not found: '+mode)
    body=re.sub(r'//[^\n]*','',match.group(1)); body=re.sub(r'/\*.*?\*/','',body,flags=re.S)
    names=re.findall(r'&Interpreter::(\w+)',body)
    if len(names)!=count: raise SystemExit(f'{mode}: expected {count} entries, got {len(names)}')
    manifest[mode]=names
    ranges=[]; start=0
    for i in range(1,len(names)+1):
        if i==len(names) or names[i]!=names[start]:
            ranges.append(f'{start:03X}-{i-1:03X} {names[start]}'); start=i
    (out/(mode+'-dispatch-ranges.txt')).write_text('\n'.join(ranges)+'\n')
    print(f'{mode}: {len(names)} entries, {len(set(names))} distinct handlers, {len(ranges)} ranges')
(out/'dispatch.json').write_text(json.dumps(manifest,indent=2)+'\n')
files=['interpreter.cpp','interpreter.h','interpreter_alu.cpp','interpreter_transfer.cpp','interpreter_branch.cpp','interpreter_lookup.cpp','memory.h','memory.cpp','core.h','core.cpp']
lines=['# Source inventory / return-expression index','',
       'Generated by tools/jit_extract_semantics.py. Macro bodies are included as source excerpts.',
       'Do not treat a return expression as a complete cycle model without its surrounding handler.', '']
for name in files:
    data=(src/name).read_bytes(); text=data.decode(); source=text.splitlines()
    lines.extend([f'## {name}',f'SHA-256: `{hashlib.sha256(data).hexdigest()}`',''])
    for i,line in enumerate(source,1):
        if 'Interpreter::' in line or re.search(r'\breturn\b',line):
            lines.append(f'{name}:{i}: {line.strip()}')
    lines.append('')
(out/'source-return-index.md').write_text('\n'.join(lines)+'\n')
