#!/usr/bin/env python3
"""Generate the native ALU allowlist from the real ARM dispatch table.
Check this file into source control; run with --check to reject table drift.
"""
import pathlib,re,sys,hashlib
root=pathlib.Path(__file__).resolve().parent.parent
raw=(root/'NooDS-Wii/interpreter_lookup.cpp').read_text()
body=re.search(r'Interpreter::armInstrs\[\]\)\(uint32_t\)\s*=\s*\{(.*?)\};',raw,re.S).group(1)
body=re.sub(r'//[^\n]*','',body)
names=re.findall(r'&Interpreter::(\w+)',body)
assert len(names)==4096
pairs=[('_and','ands'),('eor','eors'),('sub','subs'),('rsb','rsbs'),('add','adds'),('adc','adcs'),('sbc','sbcs'),('rsc','rscs'),(None,'tst'),(None,'teq'),(None,'cmp'),(None,'cmn'),('orr','orrs'),('mov','movs'),('bic','bics'),('mvn','mvns')]
classes={}
for op,pair in enumerate(pairs):
 for flag,base in enumerate(pair):
  if base:
   for suffix in ['Lli','Llr','Lri','Lrr','Ari','Arr','Rri','Rrr','Imm']:
    classes[base+suffix]=op*2+flag+1
values=[classes.get(n,0) for n in names]
text='// SPDX-License-Identifier: GPL-3.0-or-later\n// Generated by tools/jit_generate_decode.py; do not edit.\n'
text+='// Dispatch-name SHA256: '+hashlib.sha256('\n'.join(names).encode()).hexdigest()+'\n'
text+='static const uint8_t armAluClass[4096] = {\n'
text+=''.join('    '+', '.join(str(x) for x in values[i:i+16])+',\n' for i in range(0,len(values),16))
text+='};\n'
path=root/'NooDS-Wii/jit_decode_arm.inc'
if '--check' in sys.argv:
 if not path.exists() or path.read_text()!=text: raise SystemExit('ARM decode table drift; regenerate/review')
else:path.write_text(text)
print('ARM_DECODE_OK:',sum(x!=0 for x in values),'native-eligible table slots (PC operands still excluded)')
